name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make g++
          pip install conan==2.21.0

      - name: Detect Conan profile
        run: conan profile detect

      - name: Export libfoo
        run: conan export libfoo

      - name: Create libbar
        run: conan create libbar -o libfoo/*:single_precision=True --build=missing

      - name: Install dependencies for the project
        run: conan install . --build=missing -o libfoo/*:single_precision=False

      - name: Configure CMake
        run: cmake --fresh --preset conan-release

      - name: Build project
        run: cmake --build --preset conan-release
